### PR TITLE
a6000: enable wfd to fix screencast

### PR DESCRIPTION
**Pull request by BloodRedTape**

### CODE REVIEW

**Comment by Akianonymus** [comment]
does this really works ?

**Comment by dev-harsh1998** [comment]
@Akianonymus https://review.lineageos.org/q/topic:"pie-aosp-wfd"

**Review by dev-harsh1998 — APPROVED** [review]

**Comment by Akianonymus** [comment]
@dev-harsh1998 ok, gotta merge in my tree 😂

**Comment by ghostrider-reborn** [comment]
> @dev-harsh1998 ok, gotta merge in my tree

do manual testing before that
just ask some user to add those 2 props in buildprop and test screencast
nowadays most people have smart TV

**Comment by ghostrider-reborn** [comment]
cause i saw some commits in LOS which were saying that AOSP nuked wfd support and now needs new QCOM pie wfd blobs etc

**Pull request merged**
