### PR TITLE
Update bdroid_buildcfg.h

### PR DESCRIPTION
**Pull request by Anurag-Jangid**
I know it will have no effect, but please accept my pull request I just changed the A6000 to a6000. Actually I want to participate in a competition and some pull requests are required to be eligible for this competition.
Please...........Please.................Please

### CODE REVIEW

**Comment by SiddharthBharadwaj** [comment]
@dev-harsh1998 ploxx gib me 69 free t-shirts

**Comment by z3nitsu** [comment]
🤣🤣🤣

**Comment by UtsavBalar1231** [comment]
https://github.com/pappschlumpf/SmurfKernelNote20Ultra

**Comment by UtsavBalar1231** [comment]
use this to create pull requests

**Comment by Rasenkai** [comment]
Marking pull req as spam wen

**Comment by fadlyas07** [comment]
Menyesal kesal ~.~

**Review by takarushi — CHANGES_REQUESTED** [review]
This pull request shouldn't be accepted and needs to be kept with the `invalid` and `spam` tags since its was merely done to win the free t-shirt of Hacktober 2020 on the easy way without doing a big contribution at all.

**Comment by dev-harsh1998** [comment]
This pull request serves no purpose and degrades value, Changing LOC should be done after giving a proper thought and discussion, Hence this is marked as invalid and closed please tell harry to Fu©k off back at iit

**Pull request closed without merging**
