### PR TITLE
a6000: Carbon-ify

### PR DESCRIPTION
**Pull request by mayankbali**
some changes in the tree

### CODE REVIEW

**Comment by darshan1205** [comment]
..

**Comment by karthick111** [comment]
MayankBali sir knows nothing ;_;

**Comment by TheHardGamer** [comment]
Ohoooooo hohohohoh

ヽ( ° ͜ʖ͡°)ﾉ ʀuʙ ᴍʏ ᴅᴏɴɢᴇʀ ヽ( ° ͜ʖ͡°)ﾉ

**Comment by mayankbali** [comment]
That's coz I'm learning....sorry I made a mistake

**Comment by darshan1205** [comment]
gaymer

**Pull request closed without merging**
