### PR TITLE
reverted to old.

### PR DESCRIPTION
**Pull request by MRTHAKER**
revert file to old and useful.

### CODE REVIEW

**Review by darshan1205 — COMMENTED** [review]
-69

**Comment by darshan1205** [comment]
Very helpful

**Comment by karthick111** [comment]
Yes

**Comment by harry8242** [comment]
Pru thekkur

**Comment by chaubeyprateek** [comment]
Pull request again to get it merged

**Comment by MRTHAKER** [comment]
lol

**Comment by iamsj7** [comment]
@MRTHAKER Thaker is Pru AF 
/runz

Me ez noob AF
/walkz

**Comment by MRTHAKER** [comment]
@iamsj7 old days bro.

**Comment by iamsj7** [comment]
@MRTHAKER Even u iz pru in flirting ( Five Start Groups ) 😂

**Pull request closed without merging**
